// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    TmApp: typeof import('./components/tm-app/tm-app.vue')['default']
    TmCol: typeof import('./components/tm-col/tm-col.vue')['default']
    TmDivider: typeof import('./components/tm-divider/tm-divider.vue')['default']
    TmDrawer: typeof import('./components/tm-drawer/tm-drawer.vue')['default']
    TmIcon: typeof import('./components/tm-icon/tm-icon.vue')['default']
    TmModal: typeof import('./components/tm-modal/tm-modal.vue')['default']
    TmOverlay: typeof import('./components/tm-overlay/tm-overlay.vue')['default']
    TmResult: typeof import('./components/tm-result/tm-result.vue')['default']
    TmRow: typeof import('./components/tm-row/tm-row.vue')['default']
    TmSheet: typeof import('./components/tm-sheet/tm-sheet.vue')['default']
    TmSpin: typeof import('./components/tm-spin/tm-spin.vue')['default']
    TmTag: typeof import('./components/tm-tag/tm-tag.vue')['default']
    TmText: typeof import('./components/tm-text/tm-text.vue')['default']
    TmTranslate: typeof import('./components/tm-translate/tm-translate.vue')['default']
  }
}

export { }
